/**
 * canonicalBlocks.js — generated sections inside the prose documentation
 * REIT Target AI | NMIMS B.Sc. Finance — BA Theme 4.  ALL DATA IS SYNTHETIC.
 *
 * WHY
 * ---
 * The earlier drift test searched documents for a handful of exact stale
 * strings ("₹450 Cr", "18 market segments"). It missed every variant — "18
 * markets", "seven cities", "₹31.4 Cr", "Student: KJ" — so the README could
 * claim the documentation was synchronised while the project report described
 * an older project.
 *
 * Now the figures a document states are not typed at all. A document marks a
 * section:
 *
 *     <!-- canonical:BEGIN key-figures -->
 *     ...anything...
 *     <!-- canonical:END key-figures -->
 *
 * and buildMeta.js replaces its contents with a block rendered from
 * meta.json. tests/reit-tests.js renders the same blocks and fails if any
 * document's block differs, so a stale block cannot be committed silently.
 *
 * Pure: no file access. buildMeta.js and the tests do the reading and writing.
 */

"use strict";

function pct(x, dp) { return (x * 100).toFixed(dp === undefined ? 2 : dp) + "%"; }
function cr(rs, dp) { return "₹" + (rs / 1e7).toFixed(dp === undefined ? 2 : dp) + " Cr"; }
function num(n) { return Number(n).toLocaleString("en-IN"); }

/** Render every named block from meta.json. */
function render(meta) {
  var c = meta.counts, g = meta.governance, sv = meta.sourceVerification;
  var blocks = {};

  blocks["key-figures"] = [
    "| Fact | Value |",
    "|---|---|",
    "| Market segments | " + c.marketCount + " across " + c.cityCount + " cities and " + c.propertyTypeCount + " property types |",
    "| Simulated market observations | " + num(c.observationCount) + " (" + c.observationsPerMarketMin + "–" + c.observationsPerMarketMax + " per segment) |",
    "| Sample portfolio | " + c.assetCount + " holdings, " + cr(c.portfolioValueRs) + " value, " + cr(c.portfolioRentRs, 3) + " annual rent, " + pct(c.portfolioWeightedYield, 3) + " weighted gross yield |",
    "| Default investment | " + cr(c.portfolioValueRs * 0.10) + " (10% of the sample portfolio) |",
    "| Gemini agents | " + c.agentCount + " (" + meta.agents.map(function (a) { return a.label; }).join("; ") + ") |",
    "| Weight presets | " + c.presetCount + " (" + meta.presets.map(function (p) { return p.label; }).join(", ") + ") |",
    "| Simulation-support screen | " + g.rule + " — " + meta.presets[0].eligibleCount + " of " + c.marketCount + " segments pass |",
    "| External calibration | " + sv.verified + " of " + sv.externalSources + " cited external sources verified; all " + c.marketCount + " segments " + c.externalCalibrationStatus + " |",
    "| Known synthetic anomalies | " + c.plantedAnomalies + " (" + c.contaminationPct + "% of observations) |",
    "| Generator / seed / data as of | " + c.generatorVersion + " / " + c.seed + " / " + c.dataAsOf + " |",
    "| Institution and author | " + meta.project.institution + " " + meta.project.programme + ", " + meta.project.course + " — " + meta.project.author + " |"
  ].join("\n");

  blocks["preset-results"] = [
    "| Preset | Highest raw-score market | Screen | Shortlist candidate (raw rank) | Score | Gross yield | City HHI after | Asset-type HHI after |",
    "|---|---|---|---|---|---|---|---|"
  ].concat(meta.presets.map(function (p) {
    return "| " + p.label + " | " + p.highestRaw.name + " (" + p.highestRaw.score + ") | " +
      (p.highestRaw.passes ? "passes" : "fails (" + (p.highestRaw.failsOn === "both"
        ? "simulated observations and support grade" : p.highestRaw.failsOn) + ")") + " | " +
      p.candidate.name + " (" + p.candidate.rawRank + ") | " + p.candidate.score + " | " +
      p.candidate.grossYieldPct + "% | " + p.candidate.cityHHIAfter + " | " + p.candidate.typeHHIAfter + " |";
  })).concat([
    "",
    "All at the defaults: sample portfolio, " + cr(c.portfolioValueRs * 0.10) + ", screen applied, automatic selection. " +
    "Generated by `data-pipeline/scripts/buildMeta.js` from the same `analysisRun.js` the application uses."
  ]).join("\n");

  var t = meta.terminology.terms;
  blocks["terminology"] = [
    "| Term | Meaning |",
    "|---|---|"
  ].concat(Object.keys(t).map(function (k) {
    return "| " + t[k].label + " | " + t[k].definition + " |";
  })).join("\n");

  /* The customer, problem and use cases, in the words the Overview shows
   * (AppMeta.CUSTOMER, copied into meta.json by buildMeta.js). */
  var PAGE_NAMES = { overview: "Overview", portfolio: "Portfolio", screener: "Market Screener",
                     diversification: "Diversification", agents: "Agent Output", report: "Decision Report" };
  if (meta.customer) {
    blocks["customer-and-use-cases"] = [
      "**Primary user.** " + meta.customer.primaryUser,
      "",
      "**Business problem.** " + meta.customer.businessProblem,
      "",
      "**Core use cases** (and the pages where each is carried out):",
      ""
    ].concat(meta.customer.useCases.map(function (u, i) {
      return (i + 1) + ". " + u.text + " *(" + u.pages.map(function (p) { return PAGE_NAMES[p] || p; }).join(", ") + ")*";
    })).join("\n");
  }

  /* Statistical findings from statistics.json (copied into meta.json). */
  if (meta.statistics) {
    var st = meta.statistics, types = ["Commercial Office", "Retail", "Residential"];
    var r2 = st.regression.byPropertyType.map(function (m) { return m.r2; });
    blocks["statistics-summary"] = [
      "Correlations across the " + num(st.totalObservations) + " simulated market observations, pooled and within each property type:",
      "",
      "| Relationship | Expected sign | Pooled | " + types.join(" | ") + " | Sign reverses when pooled |",
      "|---|---|---|---|---|---|---|"
    ].concat(st.simpsonsParadox.map(function (r) {
      return "| " + r.label + " | " + r.expect + " | " + r.pooled.toFixed(3) + " | " +
        types.map(function (t) { return r.byPropertyType[t].toFixed(3); }).join(" | ") + " | " +
        (r.signFlip ? "yes" : "no") + " |";
    })).concat([
      "",
      "Linear regression of gross yield on rental growth: pooled slope " + st.regression.pooled.slope.toFixed(3) +
        " with R² " + st.regression.pooled.r2.toFixed(3) + "; within property types R² ranges from " +
        Math.min.apply(null, r2).toFixed(3) + " to " + Math.max.apply(null, r2).toFixed(3) + ".",
      "",
      "Detection of the " + st.anomalies.count + " known synthetic anomalies (" + st.anomalies.contaminationPct +
        "% of observations), scored against the generator's separate ground-truth file:",
      "",
      "| Detector | Flagged | Correctly flagged | Precision | Recall | F1 |",
      "|---|---|---|---|---|---|"
    ]).concat(st.detectors.map(function (d) {
      return "| " + d.method + " | " + d.flagged + " | " + d.truePositives + " | " + d.precision.toFixed(3) +
        " | " + d.recall.toFixed(3) + " | " + d.f1.toFixed(3) + " |";
    })).concat([
      "",
      "Generated by `data-pipeline/scripts/buildMeta.js` from `public/data/statistics.json`. These describe the generator's construction, not a real market."
    ]).join("\n");
  }

  /* Benchmark comparisons (data-pipeline/benchmark_checks.csv). */
  if (meta.benchmarkChecks && meta.benchmarkChecks.length) {
    var bc = meta.benchmarkChecks;
    var tally = {};
    bc.forEach(function (b) { var k = b.relation.replace(/ \(.*\)$/, ""); tally[k] = (tally[k] || 0) + 1; });
    blocks["benchmark-checks"] = [
      "| Check | Segment | Parameter | Project assumption | Located figure (quoted) | Source | Relation |",
      "|---|---|---|---|---|---|---|"
    ].concat(bc.map(function (b) {
      return "| " + b.id + " | " + b.segment + " | " + b.parameter + " | " + b.project + " " + b.units + " | " +
             b.figure.replace(/\|/g, "/") + " | " + b.publisher + ", " + b.document + " (" + b.date + "), " + b.page + " | " + b.relation + " |";
    })).concat([
      "",
      bc.length + " comparisons: " + Object.keys(tally).sort().map(function (k) { return tally[k] + " " + k; }).join(", ") +
      ". Generated from `data-pipeline/benchmark_checks.csv`, which also records each document's URL and its relationship to the source register. " +
      "None of these documents is the one the register cites, so no source is verified and every segment's external calibration stays Unverified; no assumption was changed to match a figure."
    ]).join("\n");
  }

  /* The fixed list the application shows (validator.js LIMITATIONS). */
  if (meta.limitations) {
    blocks["stated-limitations"] = meta.limitations.map(function (l, i) {
      return (i + 1) + ". " + l;
    }).join("\n");
  }

  blocks["screen-and-calibration"] = [
    "- **Composite attractiveness score** — the five weighted factors. Never changed by the screen.",
    "- **Simulation support** — simulated observations behind a segment's medians, their P10–P90 spread, " +
      "and the project's own " + meta.terminology.supportGrades.label + " (A–E). " + g.rationale,
    "- **Simulation-support screen** — " + g.rule + ". " + meta.presets[0].eligibleCount + " of " + c.marketCount + " segments pass.",
    "- **External calibration** — from the source register only: " + sv.summary + " Every segment is " +
      c.externalCalibrationStatus + ".",
    "- **Wording** — the model output is a *shortlist candidate*: \"" + meta.terminology.candidateCaveat + "\""
  ].join("\n");

  return blocks;
}

var BLOCK_RE = /(<!-- canonical:BEGIN ([a-z0-9-]+) -->)[\s\S]*?(<!-- canonical:END \2 -->)/g;

/** Replace every marked block in a document. Unknown block names are left as they are. */
function fill(text, blocks) {
  return text.replace(BLOCK_RE, function (all, begin, name, end) {
    if (!Object.prototype.hasOwnProperty.call(blocks, name)) { return all; }
    return begin + "\n" + blocks[name] + "\n" + end;
  });
}

/** Names of the blocks a document contains. */
function names(text) {
  var out = [], m;
  var re = new RegExp(BLOCK_RE.source, "g");
  while ((m = re.exec(text)) !== null) { out.push(m[2]); }
  return out;
}

/** The documents that carry generated blocks. */
var DOCUMENTS = [
  "README.md",
  "HANDOFF.md",
  "docs/project-report.md",
  "docs/data-documentation.md",
  "docs/architecture.md",
  "docs/viva-guide.md",
  "docs/limitations.md",
  "docs/prompt-design.md",
  "docs/test-report.md",
  "docs/SOURCE_VERIFICATION_REPORT.md",
  "docs/LIVE_DEMO_RUNBOOK.md"
];

module.exports = { render: render, fill: fill, names: names, DOCUMENTS: DOCUMENTS };
