/**
 * canonicalBlocks.js — generated sections inside the prose documentation
 * REIT Target AI | NMIMS B.Sc. Finance — BA Theme 4.  ALL DATA IS SYNTHETIC.
 *
 * WHY
 * ---
 * The earlier drift test searched documents for a handful of exact stale
 * strings ("₹450 Cr", "18 market segments"). It missed every variant — "18
 * markets", "seven cities", "₹31.4 Cr", "Student: KJ" — so the README could
 * claim the documentation was synchronised while the project report described
 * an older project.
 *
 * Now the figures a document states are not typed at all. A document marks a
 * section:
 *
 *     <!-- canonical:BEGIN key-figures -->
 *     ...anything...
 *     <!-- canonical:END key-figures -->
 *
 * and buildMeta.js replaces its contents with a block rendered from
 * meta.json. tests/reit-tests.js renders the same blocks and fails if any
 * document's block differs, so a stale block cannot be committed silently.
 *
 * Pure: no file access. buildMeta.js and the tests do the reading and writing.
 */

"use strict";

function pct(x, dp) { return (x * 100).toFixed(dp === undefined ? 2 : dp) + "%"; }
function cr(rs, dp) { return "₹" + (rs / 1e7).toFixed(dp === undefined ? 2 : dp) + " Cr"; }
function num(n) { return Number(n).toLocaleString("en-IN"); }

/** Render every named block from meta.json. */
function render(meta) {
  var c = meta.counts, g = meta.governance, sv = meta.sourceVerification;
  var blocks = {};

  blocks["key-figures"] = [
    "| Fact | Value |",
    "|---|---|",
    "| Market segments | " + c.marketCount + " across " + c.cityCount + " cities and " + c.propertyTypeCount + " property types |",
    "| Simulated market observations | " + num(c.observationCount) + " (" + c.observationsPerMarketMin + "–" + c.observationsPerMarketMax + " per segment) |",
    "| Sample portfolio | " + c.assetCount + " holdings, " + cr(c.portfolioValueRs) + " value, " + cr(c.portfolioRentRs, 3) + " annual rent, " + pct(c.portfolioWeightedYield, 3) + " weighted gross yield |",
    "| Default investment | " + cr(c.portfolioValueRs * 0.10) + " (10% of the sample portfolio) |",
    "| Gemini agents | " + c.agentCount + " (" + meta.agents.map(function (a) { return a.label; }).join("; ") + ") |",
    "| Weight presets | " + c.presetCount + " (" + meta.presets.map(function (p) { return p.label; }).join(", ") + ") |",
    "| Simulation-support screen | " + g.rule + " — " + meta.presets[0].eligibleCount + " of " + c.marketCount + " segments pass |",
    "| External calibration | " + sv.verified + " of " + sv.externalSources + " cited external sources verified; all " + c.marketCount + " segments " + c.externalCalibrationStatus + " |",
    "| Known synthetic anomalies | " + c.plantedAnomalies + " (" + c.contaminationPct + "% of observations) |",
    "| Generator / seed / data as of | " + c.generatorVersion + " / " + c.seed + " / " + c.dataAsOf + " |",
    "| Institution and author | " + meta.project.institution + " " + meta.project.programme + ", " + meta.project.course + " — " + meta.project.author + " |"
  ].join("\n");

  blocks["preset-results"] = [
    "| Preset | Highest raw-score market | Screen | Shortlist candidate (raw rank) | Score | Gross yield | City HHI after | Asset-type HHI after |",
    "|---|---|---|---|---|---|---|---|"
  ].concat(meta.presets.map(function (p) {
    return "| " + p.label + " | " + p.highestRaw.name + " (" + p.highestRaw.score + ") | " +
      (p.highestRaw.passes ? "passes" : "fails (" + (p.highestRaw.failsOn === "both"
        ? "simulated observations and support grade" : p.highestRaw.failsOn) + ")") + " | " +
      p.candidate.name + " (" + p.candidate.rawRank + ") | " + p.candidate.score + " | " +
      p.candidate.grossYieldPct + "% | " + p.candidate.cityHHIAfter + " | " + p.candidate.typeHHIAfter + " |";
  })).concat([
    "",
    "All at the defaults: sample portfolio, " + cr(c.portfolioValueRs * 0.10) + ", screen applied, automatic selection. " +
    "Generated by `data-pipeline/scripts/buildMeta.js` from the same `analysisRun.js` the application uses."
  ]).join("\n");

  var t = meta.terminology.terms;
  blocks["terminology"] = [
    "| Term | Meaning |",
    "|---|---|"
  ].concat(Object.keys(t).map(function (k) {
    return "| " + t[k].label + " | " + t[k].definition + " |";
  })).join("\n");

  blocks["screen-and-calibration"] = [
    "- **Composite attractiveness score** — the five weighted factors. Never changed by the screen.",
    "- **Simulation support** — simulated observations behind a segment's medians, their P10–P90 spread, " +
      "and the project's own " + meta.terminology.supportGrades.label + " (A–E). " + g.rationale,
    "- **Simulation-support screen** — " + g.rule + ". " + meta.presets[0].eligibleCount + " of " + c.marketCount + " segments pass.",
    "- **External calibration** — from the source register only: " + sv.summary + " Every segment is " +
      c.externalCalibrationStatus + ".",
    "- **Wording** — the model output is a *shortlist candidate*: \"" + meta.terminology.candidateCaveat + "\""
  ].join("\n");

  return blocks;
}

var BLOCK_RE = /(<!-- canonical:BEGIN ([a-z0-9-]+) -->)[\s\S]*?(<!-- canonical:END \2 -->)/g;

/** Replace every marked block in a document. Unknown block names are left as they are. */
function fill(text, blocks) {
  return text.replace(BLOCK_RE, function (all, begin, name, end) {
    if (!Object.prototype.hasOwnProperty.call(blocks, name)) { return all; }
    return begin + "\n" + blocks[name] + "\n" + end;
  });
}

/** Names of the blocks a document contains. */
function names(text) {
  var out = [], m;
  var re = new RegExp(BLOCK_RE.source, "g");
  while ((m = re.exec(text)) !== null) { out.push(m[2]); }
  return out;
}

/** The documents that carry generated blocks. */
var DOCUMENTS = [
  "README.md",
  "HANDOFF.md",
  "docs/project-report-draft.md",
  "docs/data-documentation.md",
  "docs/architecture.md",
  "docs/viva-guide.md",
  "docs/limitations.md",
  "docs/prompt-design.md",
  "docs/test-report.md"
];

module.exports = { render: render, fill: fill, names: names, DOCUMENTS: DOCUMENTS };
