/**
 * runbookExpected.js — the live-demo runbook's expected results, computed with
 * the application's own shared analysis run (analysisRun.js) at full precision.
 * NMIMS B.Sc. Finance — BA Theme 4 (Academic Demo). ALL DATA IS SYNTHETIC.
 *
 * Every figure the runbook quotes for exercises A, B and C comes from here and
 * is rounded only for display. tests/reit-tests.js (T-178) recomputes HHI,
 * weighted yield, year-0 rent and the base-case projection for the same
 * exercises by an independent route and compares them with this file, and
 * checks that the runbook quotes these values.
 *
 * Run: node data-pipeline/scripts/runbookExpected.js
 */
"use strict";

var fs = require("fs");
var path = require("path");
var PROJECT = path.join(__dirname, "..", "..");
var AR = require(path.join(PROJECT, "public", "js", "analysisRun.js"));

function rd(p) { return JSON.parse(fs.readFileSync(path.join(PROJECT, p), "utf8")); }
var meta = rd("public/data/meta.json");
function data(over) {
  return Object.assign({ marketsDoc: rd("public/data/markets.json"), sampleAssets: rd("public/data/portfolio.json").assets,
    portfolioMode: "sample", customAssets: [], statisticsDoc: rd("public/data/statistics.json"),
    sourceOutcomes: (meta.sourceVerification && meta.sourceVerification.outcomes) || {} }, over || {});
}

/* Exercise B's custom portfolio, exactly as typed into the Portfolio form. */
var CUSTOM = [
  { assetId: "EX-1", assetName: "Exercise Office A", city: "Mumbai", locality: "Andheri East", assetType: "Commercial Office",
    propertyValue: 60e7, annualRent: 4.2e7, totalArea: 300000, occupiedArea: 285000, occupancyRate: 0.95, leaseExpiry: "2030-03-31", tenantSector: "IT" },
  { assetId: "EX-2", assetName: "Exercise Mall B", city: "Pune", locality: "Kharadi", assetType: "Retail",
    propertyValue: 30e7, annualRent: 2.1e7, totalArea: 150000, occupiedArea: 135000, occupancyRate: 0.90, leaseExpiry: "2029-06-30", tenantSector: "Retail" },
  { assetId: "EX-3", assetName: "Exercise Homes C", city: "Bengaluru", locality: "Whitefield", assetType: "Residential",
    propertyValue: 10e7, annualRent: 0.4e7, totalArea: 80000, occupiedArea: 72000, occupancyRate: 0.90, leaseExpiry: "2028-12-31", tenantSector: "Residential" }
];

function snap(id, label, inputs, d) {
  var r = AR.compute(inputs, d || data());
  var t = AR.selected(r), rec = AR.recommended(r), raw = AR.rawLeader(r);
  var base3 = (r.portfolio.totalValueRs + r.investmentRs) * Math.pow(1.08, 3);
  return {
    id: id, label: label, inputs: inputs,
    portfolio: { valueRs: r.portfolio.totalValueRs, rentRs: r.portfolio.annualRentRs, weightedYield: r.portfolio.weightedYield, assets: r.portfolio.assetCount },
    investmentRs: r.investmentRs,
    highestRaw: { id: raw.marketId, name: AR.name(raw), score: raw.totalScore, passes: raw.governance.eligible, reasons: raw.governance.reasons },
    candidate: rec ? { id: rec.marketId, name: AR.name(rec), rawRank: rec.rank, eligibleRank: rec.eligibleRank, score: rec.totalScore } : null,
    selected: { id: t.marketId, name: AR.name(t), mode: r.selectionMode, rawRank: t.rank, eligibleRank: t.eligibleRank,
                score: t.totalScore, grossYield: t.grossYield, observations: t.observationCount, grade: t.confidenceGrade,
                city: t.city, type: t.propertyType },
    hhi: { cityBefore: r.hhi.cityBefore, cityAfter: r.hhi.cityAfter, typeBefore: r.hhi.typeBefore, typeAfter: r.hhi.typeAfter,
           weightedYieldBefore: r.hhi.weightedYieldBefore, weightedYieldAfter: r.hhi.weightedYieldAfter },
    year0RentRs: r.projections.year0AnnualRentRs,
    base3yValueRs: base3,
    scenarioKey: r.scenarioKey,
    validation: r.validation.summary,
    selectionDiffers: !!r.selectionDiffers,
    top5: r.ranked.slice(0, 5).map(function (m) { return { rank: m.rank, name: AR.name(m), score: m.totalScore, passes: m.governance.eligible }; })
  };
}

var out = {
  note: "Generated by data-pipeline/scripts/runbookExpected.js with the application's analysisRun.js. Full precision; round only for display.",
  exercises: [
    snap("start", "Balanced, default amount", { preset: "balanced" }),
    snap("A1", "Balanced, ₹75 Cr", { preset: "balanced", investmentCr: 75 }),
    snap("A2", "Custom 35/25/20/10/10, ₹75 Cr", { preset: "custom", investmentCr: 75,
      weights: { yieldWeight: 0.35, growthWeight: 0.25, diversWeight: 0.20, demandWeight: 0.10, riskWeight: 0.10 } }),
    snap("B", "Custom three-asset portfolio, Balanced, default amount", { preset: "balanced" }, data({ portfolioMode: "custom", customAssets: CUSTOM })),
    snap("B-explicit", "Custom portfolio after the user had typed ₹75 Cr", { preset: "balanced", investmentCr: 75 }, data({ portfolioMode: "custom", customAssets: CUSTOM })),
    snap("C1", "Manual Ambattur, Balanced", { schemaVersion: 2, preset: "balanced", selectionMode: "manual", manualTargetId: "MKT-036" }),
    snap("C2", "Manual Ambattur kept after pressing Income Focused", { schemaVersion: 2, preset: "incomeFocused", selectionMode: "manual", manualTargetId: "MKT-036" }),
    snap("live", "Live Gemini configuration: Diversification Focused, ₹75 Cr", { preset: "diversFocused", investmentCr: 75 })
  ],
  customPortfolio: CUSTOM
};
fs.mkdirSync(path.join(PROJECT, "data-pipeline", "generated"), { recursive: true });
fs.writeFileSync(path.join(PROJECT, "data-pipeline", "generated", "runbook_expected.json"), JSON.stringify(out, null, 2) + "\n");
out.exercises.forEach(function (e) {
  console.log(e.id.padEnd(11), e.selected.name.padEnd(34), "raw", e.selected.rawRank, "elig", e.selected.eligibleRank,
    "score", e.selected.score.toFixed(2), "gy", (e.selected.grossYield * 100).toFixed(4) + "%",
    "HHI", e.hhi.cityAfter.toFixed(4), e.hhi.typeAfter.toFixed(4), "wy", (e.hhi.weightedYieldAfter * 100).toFixed(3) + "%",
    "y0", (e.year0RentRs / 1e7).toFixed(4), "3y", (e.base3yValueRs / 1e7).toFixed(2), "inv", e.investmentRs / 1e7, "key", e.scenarioKey);
});
